- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: |-
    {{ not (lookup('env', 'MOLECULE_DEBUG') | bool or
       molecule_yml.provisioner.log|default(false) | bool) }}
  roles:
    - name: molecule_openstack_ci
      vars:
        molecule_openstack_ci_state: present
