dependency:
  name: galaxy
driver:
  name: openstack
lint:
  name: yamllint
  options:
    config-file: tests/yamllint.yml
platforms:
  - name: test-molecule_openstack_ci
    image: rhel-7.5-server-x86_64-updated
    flavor: m1.medium
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  lint:
    name: flake8
